name: syn

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * *

permissions:
  contents: write

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@master
      - name: Syn js
        run: sh syn.sh
      - name: Commit file
        run: |
          git config --global user.email dianmianqizi@qq.com
          git config --global user.name dianmianqizi
          git add .
          git commit -m"action:`date`"
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
